config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
RedmineApp::Application.routes.draw do

  post 'groups/:id/create_global_role', :controller => 'groups', :action => 'create_global_role', :id => /\d+/
  delete 'groups/:id/destroy_global_role/:rid', :controller => 'groups', :action => 'destroy_global_role', :id => /\d+/, :rid => /\d+/

  post 'users/:id/create_global_role', :controller => 'users', :action => 'create_global_role', :id => /\d+/
  delete 'users/:id/destroy_global_role/:rid', :controller => 'users', :action => 'destroy_global_role', :id => /\d+/, :rid => /\d+/

   resources :roles do
     member do
       get 'autocomplete_for_user'
       get 'autocomplete_for_user_global'
     end
   end

  get 'roles/:id/show_users_by_global_role', :controller => 'roles', :action => 'show_users_by_global_role', :id => /\d+/
  post 'roles/:id/create_global_role', :controller => 'roles', :action => 'create_global_role', :id => /\d+/
  delete 'roles/:id/destroy_global_role/:gr_id', :controller => 'roles', :action => 'destroy_global_role', :id => /\d+/, :gr_id => /\d+/

  get 'roles/:id/show_users_by_role', controller: 'roles', :action => 'show_users_by_role', :id => /\d+/
  post 'roles/:id/add_user_to_role', controller: 'roles', :action => 'add_user_to_role', :id => /\d+/
  get 'roles/:id/edit_user_projects_by_role/:user_id', controller: 'roles', action: 'edit_user_projects_by_role', :id => /\d+/, :user_id => /\d+/
  put 'roles/:id/update_user_projects_by_role', controller: 'roles', action: 'update_user_projects_by_role', :id => /\d+/
  delete 'roles/:id/remove_user_from_role/:user_id', controller: 'roles', :action => 'remove_user_from_role', :id => /\d+/, :user_id => /\d+/

end

app/models/global_role.rb
class GlobalRole < ActiveRecord::Base
  belongs_to :role
  belongs_to :principal, foreign_key: :user_id
  validates_uniqueness_of :user_id, scope: :role_id

  attr_protected :id
end

app/helpers/global_roles_helper.rb
module GlobalRolesHelper

  def authorized_globaly_to?(controller, action)
    User.current.global_permission_to?(controller, action)
  end

  def authorized_globaly?
    if User.current.global_permission_to?(params[:controller], params[:action])
      true
    else
      render_403
    end
  end

  def link_to_if_global_authorized(name, options = {}, html_options = nil, *parameters_for_method_reference)
    link_to(name, options, html_options, *parameters_for_method_reference) if User.current.global_permission_to?(options[:controller] || params[:controller], options[:action])
  end

  def roles_tabs
    tabs = [ {name: 'roles_edit', partial: 'roles/edit_tab', label: :label_permissions},
             {name: 'users_by_global_role', partial: 'roles/show_users_by_global_role', label: :label_users_by_global_role},
             {name: 'users_by_role', partial: 'roles/show_users_by_role', label: :label_users_by_role}
           ]
    return tabs
  end

  def projects_select_tag(html_id, projects)
    tag_options = options_for_select([["--- #{l(:actionview_instancetag_blank_option)} ---", '']]);
    # tag_options << options_from_collection_for_select(projects, 'id', 'name')
    tag_options << project_tree_options_for_select(projects, {})
    select_tag html_id, tag_options, class: 'glr-wide-input'
  end

  def principals_for_role_checkbox_tags(name, principals)
    html = ''
    principals.each do |principal|
      group_class = principal.instance_of?(Group) ? 'class="glr-group"' : ''
      html << "<label class='one-name'>#{check_box_tag name, principal.id, false, id: principal.id}"
      html << "<span #{group_class}>#{h principal}</span></label>\n"
    end
    html.html_safe
  end

  def render_principals_for_role(role, global = false)
    principals = Principal.active.like(params[:user_name]).order(:type, :lastname)

    if role.builtin?
      principals = principals.where('type not in(?)', ['AnonymousUser', 'GroupAnonymous', 'GroupNonMember'])
    end

    principal_count = principals.count
    principal_pages = Redmine::Pagination::Paginator.new principal_count, 100, params[:page]
    principals = principals.offset(principal_pages.offset).limit(principal_pages.per_page).to_a

    s = content_tag('div', principals_for_role_checkbox_tags('principals[]', principals), id: 'principals')

    links = pagination_links_full(principal_pages, principal_count, per_page_links: false) do |text, parameters, options|
      if !global
        link_to text, autocomplete_for_user_role_path(role, parameters.merge(user_name: params[:user_name], format: 'js')), remote: true
      else
        link_to text, autocomplete_for_user_global_role_path(role, parameters.merge(user_name: params[:user_name], format: 'js')), remote: true
      end
    end

    s + content_tag('span', links, class: 'pagination')
  end

end

app/views/groups/create_global_role.js.erb
$('#tab-content-groups-global-roles').html('<%= escape_javascript(render partial: 'roles/global_roles') %>');
<% @global_role_ids.each do |role_id| %>
  $('#role-<%= role_id %>').effect("highlight", {}, 1200);
<% end %>

app/views/groups/destroy_global_role.js.erb
$('#tab-content-groups-global-roles').html('<%= escape_javascript(render partial: 'roles/global_roles') %>');

app/views/hooks/global_roles/_head.html.erb
<% if ['usres', 'roles', 'groups'].include?(controller_name) && action_name == 'edit' %>
  <%= javascript_include_tag 'global_roles', plugin: :global_roles %>
  <%= stylesheet_link_tag 'global_roles', plugin: :global_roles %>
  <%= javascript_include_tag 'users_by_roles', plugin: :global_roles %>
<% end %>

<% if controller.controller_name == 'roles' && %w(new show edit).include?(controller.action_name) && @role %>
  <script type="text/javascript">
    RMPlus.GlobalRoles = (function (my) {
      var my = my || {};
      my.permissions = JSON.parse('<%= escape_javascript(@role.setable_permissions.inject({}) { |res, it| res[it.name] = { actions: it.actions, desc: it.description }; res }.to_json.html_safe) %>');
      my.lbl_routes = '<%= escape_javascript(l(:gr_label_routes_html)) %>';
      return my;
    })(RMPlus.GlobalRoles || {});

  </script>
  <%= javascript_include_tag :permissions, plugin: :global_roles %>
<% end %>

app/views/hooks/global_roles/_view_layouts_base_body_bottom.html.erb
<% if controller_name == 'roles' && action_name == 'edit' %>
  <% tab = params[:tab] || nil %>
  <div id="roles_tabs" class="I">
    <%= render partial: 'roles/tabs', locals: {selected: tab} %>
  </div>
<% end %>

app/views/roles/_global_roles.html.erb
<%= javascript_include_tag :global_roles, plugin: :global_roles %>
<%= stylesheet_link_tag 'global_roles', plugin: 'global_roles' %>

<%= content_tag(:div, js_err, id: 'errorExplanation') if local_assigns[:js_err] && !js_err.nil? %>

<div class="splitcontentleft" style="width:65%;">
  <% principal = @group.nil? ? @user : @group %>

  <% principal_relations = GlobalRole.joins(:principal).select("#{GlobalRole.table_name}.id, user_id, role_id, #{User.table_name}.type").where('user_id in (?)', @user ? [principal.id] + @user.groups.map(&:id) : [principal.id])  %>
  <% roles = Role.givable.where("#{Role.table_name}.id NOT IN (SELECT role_id FROM #{GlobalRole.table_name} WHERE user_id = ?)", principal.id) %>

  <% if principal_relations.any? %>
    <table class="list relations">
      <thead>
        <tr>
          <th><%= l(:label_role) %></th>
          <th style="width:15%"></th>
        </tr>
      </thead>
      <tbody>
      <% principal_relations.sort_by{|el| el.role.name.to_s}.each do |rel| %>
        <tr id="role-<%= rel.id %>" class="<%= cycle 'odd', 'even' %>">
          <td class="role-name"><%= link_to(rel.role.name, edit_role_path(rel.role)) %></td>
          <td class="buttons">
            <% if rel.type == 'Group' %>
                <%= l(:gr_label_inherit_group) %>
            <% else %>
                <%= delete_link( "destroy_global_role/#{rel.id}", remote: true ) %>
          <% end %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  <% else %>
    <p id="no_relation_groups_records" class="nodata"><%= l(:label_no_data) %></p>
  <% end %>
</div>

<div class="splitcontentright" style="width:30%;">
  <%= form_tag({action: 'create_global_role'}, {id: 'select_roles', remote: true}) do %>
    <fieldset><legend><strong> <%= l(:label_roles) %> </strong></legend>
      <p><%= text_field_tag('filter_roles', '', class: 'find-filter autocomplete') %></p>
        <div id="roles-list" class="glr-list-container">
          <% roles.sort_by{|el| el.name.to_s}.each do |r| %>
            <nobr><%= content_tag( :label,
                                   check_box_tag('roles[]', r.id, false, id: nil) + r.name.to_s,
                                   class: 'one-name' ) %></nobr>
          <% end %>
        </div>
      <p>
      <%= submit_tag(l(:label_add_item), id: 'record_add', class: 'btn-def') %>
      </p>
    </fieldset>
  <% end %>
</div>

app/views/roles/_show_users_by_global_role.html.erb
<%= content_tag(:div, js_err, id: 'errorExplanation') if local_assigns[:js_err] && !js_err.nil? %>

<div>
  <div class="splitcontentleft" style="width:65%;">
  <% principals_by_global_roles = @role.principals_by_global_roles.select("#{Principal.table_name}.*, #{GlobalRole.table_name}.id AS gr_id") %>
    <% if principals_by_global_roles != [] %>
      <table class="list relations">
        <thead>
          <tr>
            <th><%= l(:label_user) %> / <%= l(:label_group) %></th>
            <th style="width:15%"></th>
          </tr>
        </thead>
        <tbody>
        <% principals_by_global_roles.each do |principal| %>
          <tr id="principal-<%= principal.id %>" class="<%= cycle 'odd', 'even' %>">
          <% group_class = principal.instance_of?(Group) ? 'glr-group' : '' %>
            <td class="principal-name <%= group_class %>">
              <% if principal.instance_of?(User) %>
                <%= link_to(principal.name, edit_user_path(principal)) %></td>
              <% elsif !principal.instance_of?(AnonymousUser) %>
                <%= link_to(principal.name, edit_group_path(principal)) %></td>
              <% end %>
            <td class="buttons">
              <%= link_to( "<span>#{l(:button_delete)}</span>".html_safe,
                           "destroy_global_role/#{principal.attributes['gr_id']}",
                           method: :delete,
                           remote: true,
                           class: 'in_link icon icon-del' ) %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    <% else %>
      <p id="no_relation_groups_records" class="nodata"><%= l(:label_no_data) %></p>
    <% end %>
  </div>
  <div class="splitcontentright" style="width:30%;">
    <%= form_tag( {action: 'create_global_role'}, { id: 'select_users', remote: true} ) do %>
      <fieldset>
        <legend><strong> <%= l(:label_user) %> / <%= l(:label_group) %> </strong></legend>
        <p><%= text_field_tag('filter_users_global_roles', '',
                              class: 'find-filter autocomplete', data: {url: autocomplete_for_user_global_role_path(@role)}) %></p>
          <div id="users-list-global-roles" class="glr-list-container">
            <%= render_principals_for_role(@role, true) %>
          </div>
        <p>
          <%= submit_tag(l(:label_add_item), id: 'record_add') %>
        </p>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/roles/_tabs.html.erb
<%= render_tabs roles_tabs %>

app/views/roles/_user_projects_for_role_form.html.erb
<%= form_tag({controller: 'roles', action: 'update_user_projects_by_role', id: @role.id}, {method: :put, remote: true, class: 'member-projects-form'}) do %>
  <p>
    <% @projects.each do |project| %>
      <% deletable = true %>
      <% in_project = false %>
      <% role_for_project = MemberRole.joins(:member).where(members: {project_id: project.id, user_id: @principal.id}, role_id: @role.id).first %>


      <% in_project = true if role_for_project %>
      <% deletable = false if role_for_project && role_for_project.inherited_from.to_i > 0 %>

      <label><%= check_box_tag 'membership[project_ids][]', project.id, in_project, disabled: !deletable %>
        <%=h project %>
      </label><br />
    <% end %>
  </p>
  <%= hidden_field_tag 'membership[principal_id]', @principal.id, id: 'edit_user_projects_by_role_principal_id' %>
  <p>
    <%= submit_tag l(:button_change), class: 'small' %>
    <%= link_to l(:button_cancel), "#", class: 'in_link projects-form-cancel' %>
  </p>
<% end %>

app/views/roles/add_user_to_role.js.erb
$('#tab-content-users_by_role').html('<%= escape_javascript(render partial: 'roles/show_users_by_role') %>');
<% @edited_principal_ids.each do |principal_id| %>
  $('#principal-<%= principal_id %>').effect("highlight", {}, 1200);
<% end %>

app/views/roles/autocomplete_for_user.js.erb
$('#users-list').html('<%= escape_javascript(render_principals_for_role(@role, false)) %>');
var selector = $('#users-list').attr('data-checkbox-selector');
$(selector).prop('checked', 'checked');

app/views/roles/autocomplete_for_user_global.js.erb
$('#users-list-global-roles').html('<%= escape_javascript(render_principals_for_role(@role, true)) %>');
var selector = $('#users-list-global-roles').attr('data-checkbox-selector');
$(selector).prop('checked', 'checked');

app/views/roles/create_global_role.js.erb
$('#tab-content-users_by_global_role').html('<%= escape_javascript(render partial: 'roles/show_users_by_global_role') %>');
<% @principal_ids.each do |principal_id| %>
  $('#principal-<%= principal_id %>').effect("highlight", {}, 1200);
<% end %>

app/views/roles/destroy_global_role.js.erb
$('#tab-content-users_by_global_role').html('<%= escape_javascript(render partial: 'roles/show_users_by_global_role') %>');

app/views/roles/edit_user_projects_by_role.js.erb
$('#principal-<%= @principal.id %>-projects').html('<%= escape_javascript( render partial: 'user_projects_for_role_form') %>').show();

$('#principal-<%= @principal.id %> .glr-projects-names').hide();

app/views/roles/remove_user_from_role.js.erb
$('#tab-content-users_by_role').html('<%= escape_javascript(render partial: 'roles/show_users_by_role') %>');

app/views/roles/show_users_by_global_role.js.erb
$('.edit_role').after('<%= escape_javascript(render partial: 'roles/show_users_by_global_role') %>');

app/views/roles/update_user_projects_by_role.js.erb
$('#tab-content-users_by_role').html('<%= escape_javascript(render partial: 'roles/show_users_by_role') %>');
$('tr#principal-<%= @principal_id %>').effect("highlight", {}, 1200);

app/views/users/create_global_role.js.erb
$('#tab-content-users-global-roles').html('<%= escape_javascript(render :partial => 'roles/global_roles') %>');
<% @global_role_ids.each do |gr_id| %>
  $('#role-<%=gr_id%>').effect("highlight", {}, 1200);
<% end %>

app/views/users/destroy_global_role.js.erb
$('#tab-content-users-global-roles').html('<%= escape_javascript(render partial: 'roles/global_roles') %>');